name: Deploy Boutique Glenda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Generar versión
        id: version
        run: echo "VERSION=v1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Deploy en servidor
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 157.230.52.21
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/boutique-glenda-api
            git pull
            ./deploy.sh ${{ steps.version.outputs.VERSION }}